name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
        - run: cd .src/webapp/api
        - run: ls
        - run: npm run test
        